/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/context/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#47464b",
        error: "#ffb4ab",
        "surface-container-low": "#1a1b1f",
        "surface-bright": "#38393d",
        "tertiary-fixed-dim": "#c8c5cb",
        "on-secondary-fixed": "#1b1b1e",
        "tertiary-fixed": "#e4e1e7",
        "on-tertiary-container": "#3e3d42",
        "inverse-surface": "#e3e2e7",
        "on-primary": "#532200",
        "on-tertiary": "#303034",
        primary: "#ffb68d",
        "surface-dim": "#121317",
        "on-background": "#e3e2e7",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#9a4600",
        "on-surface-variant": "#ddc1b3",
        surface: "#121317",
        "on-surface": "#e3e2e7",
        "surface-container-lowest": "#0d0e12",
        "surface-container": "#1f1f24",
        outline: "#a58c7f",
        "outline-variant": "#564338",
        "primary-container": "#ff8a3d",
        "on-primary-container": "#682d00",
        "on-primary-fixed-variant": "#763300",
        tertiary: "#c8c5cb",
        "on-secondary-container": "#b6b4b8",
        "on-primary-fixed": "#321200",
        "on-tertiary-fixed": "#1b1b1f",
        "primary-fixed-dim": "#ffb68d",
        "primary-fixed": "#ffdbc9",
        "secondary-fixed-dim": "#c8c5ca",
        "secondary-container": "#47464a",
        "surface-variant": "#343439",
        "on-secondary-fixed-variant": "#47464a",
        secondary: "#c8c5ca",
        "error-container": "#93000a",
        "secondary-fixed": "#e4e1e6",
        "surface-tint": "#ffb68d",
        "inverse-on-surface": "#2f3035",
        "surface-container-high": "#292a2e",
        "surface-container-highest": "#343439",
        "tertiary-container": "#aaa8ad",
        background: "#121317",
        "on-error": "#690005",
        // product-status colors not present in Stitch's Material token set
        success: "#4ade80",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        "stack-tight": "8px",
        "card-gap": "12px",
        "stack-loose": "20px",
        "container-padding": "24px",
      },
      fontFamily: {
        "headline-md-mobile": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-sm": ["Manrope"],
        "label-caps": ["Manrope"],
        "data-point": ["Manrope"],
        "display-lg": ["Manrope"],
      },
      fontSize: {
        "headline-md-mobile": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "data-point": ["13px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.06em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};